name: harvest_guard_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.0
  image: ^4.1.0
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  hive_generator: ^2.0.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  # Menambahkan assets
  assets:
    - assets/images/
    - assets/label.txt
    - assets/model/
